FROM docker-registry.guokr.com/apps/zaih-base

ADD ./requirements/* /requirements/
WORKDIR /requirements

RUN echo "172.31.2.213 pypi.iguokr.com" >> /etc/hosts && pip install zaih-core==2017.02.23.01 -i http://pypi.iguokr.com/guokr/dev/+simple --trusted-host pypi.iguokr.com
RUN pip install -r dev.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com 

EXPOSE 8888
