"""init db

Revision ID: 53915e1efc42
Revises: None
Create Date: 2017-04-12 03:11:10.613446

"""

# revision identifiers, used by Alembic.
revision = '53915e1efc42'
down_revision = None

from alembic import op
import sqlalchemy as sa
import zaih_core


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('assistant_name', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=u'draft', nullable=False),
    sa.Column('review_status', sa.String(length=16), server_default=u'pending', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('date_published', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_start', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_end', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('column', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_date_end'), ['date_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_date_published'), ['date_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_date_start'), ['date_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_status'), ['status'], unique=False)

    op.create_table('article',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=u'draft', nullable=False),
    sa.Column('review_status', sa.String(length=16), server_default=u'pending', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('date_published', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_date_published'), ['date_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)

    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'column_id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_date_created'), ['date_created'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=16), server_default=u'column', nullable=False),
    sa.Column('order_type', sa.String(length=16), server_default=u'subscribe', nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=u'pending', nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_target_type'), ['target_type'], unique=False)

    op.create_table('assistant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(length=32), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'column_id')
    )
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_date_updated'), ['date_updated'], unique=False)

    op.create_table('liking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_id', 'target_type')
    )
    with op.batch_alter_table('liking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liking_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liking_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_liking_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liking_target_type'), ['target_type'], unique=False)

    op.create_table('voice',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('voice_key', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=16), server_default=u'article', nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=u'draft', nullable=False),
    sa.Column('review_status', sa.String(length=32), server_default=u'pending', nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_target_type'), ['target_type'], unique=False)

    op.create_table('active',
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), server_default=u'question', nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=u'active', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_target_type'), ['target_type'], unique=False)
        batch_op.create_index('ix_feed_account_id_status', ['account_id', 'status'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(length=16), server_default=u'pending', nullable=False),
    sa.Column('is_sticky', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('date_published', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_date_published'), ['date_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_is_sticky'), ['is_sticky'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_review_status'), ['review_status'], unique=False)

    op.create_table('reply',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(length=16), server_default=u'pending', nullable=False),
    sa.Column('is_sticky', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('date_published', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_updated', zaih_core.database.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reply_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_date_published'), ['date_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_is_sticky'), ['is_sticky'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_review_status'), ['review_status'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_review_status'))
        batch_op.drop_index(batch_op.f('ix_reply_post_id'))
        batch_op.drop_index(batch_op.f('ix_reply_is_sticky'))
        batch_op.drop_index(batch_op.f('ix_reply_is_hidden'))
        batch_op.drop_index(batch_op.f('ix_reply_date_updated'))
        batch_op.drop_index(batch_op.f('ix_reply_date_published'))
        batch_op.drop_index(batch_op.f('ix_reply_date_created'))
        batch_op.drop_index(batch_op.f('ix_reply_column_id'))
        batch_op.drop_index(batch_op.f('ix_reply_account_id'))

    op.drop_table('reply')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_review_status'))
        batch_op.drop_index(batch_op.f('ix_post_is_sticky'))
        batch_op.drop_index(batch_op.f('ix_post_is_hidden'))
        batch_op.drop_index(batch_op.f('ix_post_date_updated'))
        batch_op.drop_index(batch_op.f('ix_post_date_published'))
        batch_op.drop_index(batch_op.f('ix_post_date_created'))
        batch_op.drop_index(batch_op.f('ix_post_column_id'))
        batch_op.drop_index(batch_op.f('ix_post_account_id'))

    op.drop_table('post')
    with op.batch_alter_table('active', schema=None) as batch_op:
        batch_op.drop_index('ix_feed_account_id_status')
        batch_op.drop_index(batch_op.f('ix_active_target_type'))
        batch_op.drop_index(batch_op.f('ix_active_target_id'))
        batch_op.drop_index(batch_op.f('ix_active_status'))
        batch_op.drop_index(batch_op.f('ix_active_source'))
        batch_op.drop_index(batch_op.f('ix_active_date_created'))
        batch_op.drop_index(batch_op.f('ix_active_column_id'))
        batch_op.drop_index(batch_op.f('ix_active_action'))
        batch_op.drop_index(batch_op.f('ix_active_account_id'))

    op.drop_table('active')
    with op.batch_alter_table('voice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_target_type'))
        batch_op.drop_index(batch_op.f('ix_voice_target_id'))
        batch_op.drop_index(batch_op.f('ix_voice_status'))
        batch_op.drop_index(batch_op.f('ix_voice_source'))
        batch_op.drop_index(batch_op.f('ix_voice_review_status'))
        batch_op.drop_index(batch_op.f('ix_voice_date_updated'))
        batch_op.drop_index(batch_op.f('ix_voice_date_created'))

    op.drop_table('voice')
    with op.batch_alter_table('liking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liking_target_type'))
        batch_op.drop_index(batch_op.f('ix_liking_target_id'))
        batch_op.drop_index(batch_op.f('ix_liking_date_created'))
        batch_op.drop_index(batch_op.f('ix_liking_account_id'))

    op.drop_table('liking')
    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_date_updated'))
        batch_op.drop_index(batch_op.f('ix_assistant_date_created'))
        batch_op.drop_index(batch_op.f('ix_assistant_column_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_account_id'))

    op.drop_table('assistant')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_target_type'))
        batch_op.drop_index(batch_op.f('ix_order_target_id'))
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_price'))
        batch_op.drop_index(batch_op.f('ix_order_order_type'))
        batch_op.drop_index(batch_op.f('ix_order_date_updated'))
        batch_op.drop_index(batch_op.f('ix_order_date_created'))
        batch_op.drop_index(batch_op.f('ix_order_account_id'))

    op.drop_table('order')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_date_created'))
        batch_op.drop_index(batch_op.f('ix_member_column_id'))
        batch_op.drop_index(batch_op.f('ix_member_account_id'))

    op.drop_table('member')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_index(batch_op.f('ix_article_status'))
        batch_op.drop_index(batch_op.f('ix_article_review_status'))
        batch_op.drop_index(batch_op.f('ix_article_is_hidden'))
        batch_op.drop_index(batch_op.f('ix_article_date_updated'))
        batch_op.drop_index(batch_op.f('ix_article_date_published'))
        batch_op.drop_index(batch_op.f('ix_article_date_created'))
        batch_op.drop_index(batch_op.f('ix_article_column_id'))
        batch_op.drop_index(batch_op.f('ix_article_account_id'))

    op.drop_table('article')
    with op.batch_alter_table('column', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_status'))
        batch_op.drop_index(batch_op.f('ix_column_review_status'))
        batch_op.drop_index(batch_op.f('ix_column_price'))
        batch_op.drop_index(batch_op.f('ix_column_name'))
        batch_op.drop_index(batch_op.f('ix_column_is_hidden'))
        batch_op.drop_index(batch_op.f('ix_column_date_updated'))
        batch_op.drop_index(batch_op.f('ix_column_date_start'))
        batch_op.drop_index(batch_op.f('ix_column_date_published'))
        batch_op.drop_index(batch_op.f('ix_column_date_end'))
        batch_op.drop_index(batch_op.f('ix_column_date_created'))
        batch_op.drop_index(batch_op.f('ix_column_account_id'))

    op.drop_table('column')
    ### end Alembic commands ###
