swagger: '2.0'
info:
    title: Fenda Sub API
    version: '1.0.0'
schemes:
    - http
basePath:
    /v1
consumes:
    - application/json
profuces:
    - application/json
definitions:
    datetime:
        type: string
        format: datetime
    Account:
        properties:
            id:
                type: string
            nickname:
                type: string
            title:
                type: string
            avatar:
                type: string
            is_verified:
                type: boolean
    Column:
        properties:
            id:
                type: string
            name:
                type: string
            content:
                type: string
            account_id:
                type: integer
            account:
                $ref: '#/definitions/Account'
            image:
                type: string
            price:
                type: integer
            assistant_name:
                type: string
            date_published:
                $ref: '#/definitions/datetime'
            date_start:
                $ref: '#/definitions/datetime'
            date_end:
                $ref: '#/definitions/datetime'
            date_created:
                $ref: '#/definitions/datetime'
            date_updated:
                $ref: '#/definitions/datetime'
    ColumnDetail:
        allOf:
            - $ref: '#/definitions/Column'
            - type: object
        properties:
            voice_id:
                type: string
    Error:
        properties:
            error_code:
                type: string
            message:
                type: string
            text:
                type: string
    Success:
        properties:
            ok:
                type: boolean
parameters:
    AccessToken:
        name: Authorization
        in: header
        required: true
        type: string
    AccessTokenOptional:
        name: Authorization
        in: header
        required: false
        type: string
    Authorization:
        description: 格式 (Basic hashkey) 注 hashkey为client_id + client_secret 做BASE64处理
        in: header
        name: Authorization
        required: true
        type: string
    string_id_in_path:
        description: string id in path
        name: id
        in: path
        required: true
        type: string
    page:
        description: page number
        name: page
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    per_page:
        description: per_page number
        name: per_page
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    offset:
        description: offset number
        name: offset
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    limit:
        description: limit number
        name: limit
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
securityDefinitions:
    OAuth2:
        type: oauth2
        flow: password
        tokenUrl: https://apis-fd.zaih.com/v1/oauth/token
        scopes:
            open: 开放API
            panel: 后台API
            backend: Backend API
paths:
    /columns:
        get:
            summary: 专栏列表
            description: 专栏列表
            tags: [COLUMNS]
            operationdId: get_columns
            parameters:
                - $ref: '#/parameters/AccessToken'
                - $ref: '#/parameters/page'
                - $ref: '#/parameters/per_page'
                - $ref: '#/parameters/offset'
                - $ref: '#/parameters/limit'
            responses:
                200:
                    description: 专栏列表
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Column'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
    /columns/{id}:
        get:
            summary: 专栏
            description: 专栏
            tags: [COLUMNS]
            operationdId: columns
            parameters:
                - $ref: '#/parameters/AccessToken'
                - $ref: '#/parameters/string_id_in_path'
            responses:
                200:
                    description: 专栏
                    schema:
                        $ref: '#/definitions/ColumnDetail'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'
            security:
                - OAuth2: [open]
tags:
    - {description: "专栏", name: COLUMNS}
