swagger: '2.0'
info:
    title: Fenda Sub API
    version: '1.0.0'
schemes:
    - http
basePath:
    /v1
consumes:
    - application/json
profuces:
    - application/json
definitions:
    Error:
        properties:
            error_code:
                type: string
            message:
                type: string
            text:
                type: string
    Success:
        properties:
            ok:
                type: boolean
parameters:
    AccessToken:
        name: Authorization
        in: header
        required: true
        type: string
    AccessTokenOptional:
        name: Authorization
        in: header
        required: false
        type: string
    Authorization:
        description: 格式 (Basic hashkey) 注 hashkey为client_id + client_secret 做BASE64处理
        in: header
        name: Authorization
        required: true
        type: string
    page:
        description: page number
        name: page
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    per_page:
        description: per_page number
        name: per_page
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    offset:
        description: offset number
        name: offset
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
    limit:
        description: limit number
        name: limit
        in: query
        required: false
        type: integer
        format: int32
        maximum: 10000
securityDefinitions:
    OAuth2:
        type: oauth2
        flow: password
        tokenUrl: https://apis-fd.zaih.com/v1/oauth/token
        scopes:
            open: 开放API
            panel: 后台API
            backend: Backend API
paths:
tags:
    - {description: "专栏", name: OPEN_COLUMN}
